################################ my-sql ################################
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/projectorion}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.jpa.show-sql=true

################################ spring-security ################################
spring.security.user.name=${SPRING_SECURITY_USER_NAME:admin}
spring.security.user.password=${SPRING_SECURITY_USER_PASSWORD:password}

################################ jwt ################################
# jwt | jwtSecret - used in crypto graphy | 172800000 - 2 days
spring.app.jwtSecret=${SPRING_APP_JWT_SECRET:mySecretKeyd12039dad49768dfef93eee6ff27d567938c81ae8bc95c872aa6e96344cec80d}
spring.app.jwtExpirationMs=${SPRING_APP_JWT_EXPIRATION_MS:172800000}
# note change to 256 bits in case of high security

################################ email-settings ################################
spring.mail.host=${SPRING_MAIL_HOST:smtp.gmail.com}
spring.mail.port=${SPRING_MAIL_PORT:587}
spring.mail.username=${SPRING_MAIL_USERNAME:project.orion.2025@gmail.com}
spring.mail.password=${SPRING_MAIL_PASSWORD:awukzhmnojwsyksq}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

################################ others ################################
spring.application.name=project_orion
frontend.url=${FRONTEND_URL:http://localhost:3000}
logging.pattern.console = ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}

################################ MONITORING/SPRING ACTUATOR ################################
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

################################ TIMEOUT ################################
#server.connection-timeout=3000 not working
#spring.mvc.async.request-timeout=3000